### ISSUE TITLE
Szűrő kimeneti formátuma

### ISSUE THREAD

**Issue by gpetho** [ril-lexknowrep/postprocess-emtsv#3]
- [x] új, szókilistázós formátum
  :arrow_right: megoldás: https://github.com/ril-lexknowrep/postprocess-emtsv/pull/4
- [x] `\\t` + `\t` hekk megoldása
- [x] fölös szóközök törlése

__határidő:__ 2021-09-16

**Comment by gpetho** [comment]
@hetkotetes1959 az alábbiakat kérte e-mailben:

> Az output txt-t úgy szeretném megkapni, hogy a sor eleje szövegesen az legyen, hogy "plusz" vagy "mínusz". Utána egy tabbal elválasztva jöhet a mondat. Utána egy tabbal elválasztva kérem a <<problémás>> tokent. Ha van második meg harmadik stb., akkor azokat is tab válassza el egymástól.

> Az első tab előtt a "mínusz" vagy "plusz" karaktersor szerepeljen (tehát nem - meg +)

> a "plusz" karaktersorral kezdődő sorok maradjanak szépen a helyükön

Az outputformátum az eldobandó mondatokra az alábbi legyen:

> `mínusz\tEbben a <<problemas>> mondatban <<problemas>> vannak <<problemas>>\t<<problemas>>\t<<problemas>>\t<<problemas>>`

Korábbi előzmények itt: [https://github.com/ril-lexknowrep/feladatok/issues/5](https://github.com/ril-lexknowrep/feladatok/issues/5)

**Comment by gpetho** [comment]
Ezeket úgy implementálom, hogy hozzáadok a szkripthez három új parancssori kapcsolót:

- két str a pozitív, illetve negatív mondatok címkéjének,
- valamint egy bool, ez kiiratja a problémás szavakat a sor végén a mondat után.

**Comment by gpetho** [comment]
@hetkotetes1959 @sassbalint 
Legeneráltam az outputot a kért formátumban, ide tettem:
`oliphant:/bigstore/share/lexi/gpetho/MagyarHirlap_2002_10_elso_10000_mondat.simtaglist.tsv`

Az input az előző változattal megegyező volt, a pontos parancssor a következő:

`cat /home/joker/tmp/lexknowrep/arcanum_analyse/analysed/MagyarHirlap_2002_10.tsv | python3 scripts/read_first_n_sentences.py 10000 | tail -n +2 | python3 scripts/filter_emagyar.py -t -p="plusz\t" -n="mínusz\t" -i | python3 scripts/one_sentence_per_line.py > MagyarHirlap_2002_10_elso_10000_mondat.simtaglist.tsv`

Az új parancssori kapcsolókhoz pull requestet csináltam.

**Comment by sassbalint** [comment]
Elfogadtam a https://github.com/ril-lexknowrep/postprocess-emtsv/pull/4 PR-t, köszi.

Kiegészítettem a `Makefile`-t az új dolgokkal.
`check_sentence()` -- oké, legyen bool, de átcsináltam `True`-ra.
`for line in stdin:` esetén nem kell az üres sort / EOF-t ellenőrizni, pont ez benne a jó. :)

Egy kérésem van még: a `\\t` + `\t` dolog eléggé hekk, merthát ki honnan tudhatná, hogy `\t`-t kell írni, ha TAB-ot szeretnénk. Légyszi csináld át ilyenre: megnézzük, hogy a `POSMARKER/NEGMARKER` végén van-e vmi wsp, és ha van, akkor a belőle készített "álszó" `ws_after` (!) mezőjébe tegyük, és akkor sztem jó lesz minden.

**Comment by gpetho** [comment]
Lehet, hogy csak én nem értem a logikáját, de nekem ésszerűtlennek tűnik a `WORD_SEPARATOR` konstans elnevezése. Ez se nem szó (tehát nem Word osztályú objektum), se nem szavakat választ el egymástól, hanem mondatokat. Ne nevezzük át inkább `SENTENCE_SEPARATOR`-re?

Ezt eredetileg az igekötőkapcsolásos feladatba írtam [ide](https://github.com/ril-lexknowrep/feladatok/issues/6#issuecomment-912507475) bele, de nem oda tartozik, ezért átmásoltam ide. Hogy csináltad azt, hogy egy kommentet áttettél egyik issue-ból a másikba?

**Comment by sassbalint** [comment]
> Lehet, hogy csak én nem értem a logikáját, de nekem ésszerűtlennek tűnik a `WORD_SEPARATOR` konstans elnevezése. Ez se nem szó (tehát nem Word osztályú objektum), se nem szavakat választ el egymástól, hanem mondatokat. Ne nevezzük át inkább `SENTENCE_SEPARATOR`-re?

Asszem hagyjuk... olyasmi lenne, hogy _word-ök streamjében az elválasztó._

> Ezt eredetileg az igekötőkapcsolásos feladatba írtam [ide](https://github.com/ril-lexknowrep/feladatok/issues/6#issuecomment-912507475) bele, de nem oda tartozik, ezért átmásoltam ide. Hogy csináltad azt, hogy egy kommentet áttettél egyik issue-ból a másikba?

Csak így lehet, ahogy csináltad: copy-paste-delete. (Béna, de ez van.)

**Comment by gpetho** [comment]
>     1. Hasonlóan oldd meg a `rejected_words`-t is: azokból is legyenek álszavak.

Ez a része nem lesz jó. A listázott szavakkal magukkal nincs gond, de ha wsafterrel csinálom, akkor az első listázott szó előtti igazi szó (tipikusan a mondatvégi írásjel) wsafterjét módosítani kellene (hozzá kellene tapasztanom egy tabulátort), ami nincs rendben.

**Comment by gpetho** [comment]
>     a `-s/-t` kimenetben a sorok végén (ill `-i` esetén a TAB előtt) van 1-2 szóköz. Ezek a fölös szóközök ne legyenek. 
(De lehetőleg ne úgy, hogy utólag levágod, hanem a logikából jól jöjjön ki a dolog.)

Azok a szóközök ugye úgy keletkeznek, hogy a wsafterben szereplő \n részsztringeket kicseréltem egy-egy szóközre, ezért is hol egy van belőlük, hol több, attól függően, hogy a wsafterben mennyi van belőle. Azt nyilván könnyedén meg tudom csinálni regexszel, hogy mindig pontosan egy szóköz legyen (ennek nem láttam hasznát, ezért replace-szel cseréltem egyenként). Ezt szándékosan csináltam így, azt ugyanis konkrétan nem lehet kivitelezni a jelen formában, hogy töröljük a sortöréseket teljesen (lényegében ezt szeretnéd) a szóközre cserélés helyett. Ugye streamként jönnek be a szavak egymás után, és ahhoz, hogy lássam, hogy az adott szó után mondat vége jön-e (csak itt kell és egyszersmind csak itt szabad törölni a sortöréseket), előre kellene néznem a streambe. A mondat belsejében levő sortöréseket nem szabad törölni ugyanis, mert akkor összecsúsznak a sor végi és sor eleji szavak.

Az előrenézést megoldani olyan bonyolult lenne, hogy ezzel szerintem nem nyerünk semmit. Két ésszerű lehetőséget látok, mindkettő az "utólag levágom" kategória.

1. Vagy a `one_sentence_per_line.py`-ban pufferolom a bejövő szavakból konkatenált sztringet addig, amíg mondat végére nem értem, és akkor egy lépésben regexszel letisztázom az egészet, majd kiírom.
2. Vagy a `one_sentence_per_line.py`-t módosítom úgy, hogy ne csináljon semmit se a sortörésekkel, se a tabulátorokkal, csak simán fusson le, hanem utána bekötök még egy szkriptet, ami az egészet utólag regexekkel letisztázza.

Van preferenciád, hogy melyiket csináljam a kettő közül, vagy van jobb konkrét ötleted?

**Comment by gpetho** [comment]
Közben a forkomban átírtam a dokumentációt, ahogy ígértem, és kicsit belenyúltam a Makefile-ba is, ezekre esetleg pillants rá, mielőtt PR-t csinálok róluk, ha így kényelmesebb:

Makefile:

[[mod] add POSMARKER, NEGMARKER to simulate, simulate_and_tag](https://github.com/gpetho/postprocess-emtsv/commit/ff8b88066a3b75ec7bb9f9068602fdafe75229ea) : erre azért volt szükség, mert az a két kapcsoló nem a `-i`-hez tartozik, hanem a `-s/-t`-hez. Hogy így a `plusz\t`, `mínusz\t` az optimális default ezekre, nem tudom, szerintem talán inkább nem, de ezen nem változtattam.

dokumentáció:

[[mod] added make simulate_and_tag_and_list](https://github.com/gpetho/postprocess-emtsv/commit/4ae1d3bada2c9d3eb738f01db1d1a3f938279df4)

[[mod] cleaned up testing](https://github.com/gpetho/postprocess-emtsv/commit/84ebd449ba8f01862f170aa98eba64afdf5c211b) : lényegében csak hozzáigazítottam az általad a Makefile-ba tett változásokhoz, aztán rájöttem, hogy a `.txt` helyett is legyen inkább `.filt`. Ezt majd belecommitolom a Makefile-ba is nyilván, ha jó így.

**Comment by gpetho** [comment]
Mivel kedden elkészültem a párhuzamosítás átdolgozásával, szerdán ezt fogom megcsinálni, és annak megfelelően, ahogy írtad, csinálom saját belátásom szerint.

**Comment by gpetho** [comment]
Megcsináltam, amit kértél. Ahogy dolgoztam rajta, a hangsúly eltolódott afelé, hogy a filter outputjaként létrejövő xtsv-fájl az eredeti állapotára detokenizálható legyen. Ennek ellentmondott a bal és jobb címkék eredeti kezelése, azokat ugyanis simán beleírtam a `form` oszlopba. Arra gondoltam, hogy akkor csinálok ezekből is álszavakat, viszont erre meg az volt a probléma, hogy ha ezeket beteszem a megjelölt szó elé és után egy-egy álszóként, akkor a megjelölt szó `wsafter`-je miatt a jobb címke nem tapadna a tokenhez. Hosszabb töprengés után arra jutottam, hogy az igazi szót hagyom úgy, ahogy van, és utána még egy példányban beteszem az outputba kiegészítve a bal és jobb címkével, az egészet egy álszóként.

Mivel a mondatvégi whitespace eltávolításához eleve hasznos lett volna az előrenézés, ezt végül így implementáltam, annyira egyáltalán nem lett bonyolult, mint ahogy elképzeltem. Egyszersmind az előrenézést használtam fel a felcímkézett szavak megjelenítésére is: ha egymást követi az xtsv-fájlban a Kostunica szó és utána a <<Kostunica>> álszó, akkor csak az utóbbit írja ki a formázott outputba.

A sorvégi szóközöket mindenesetre megoldottam az előrenézéssel. Ugyanilyen szóközök vannak viszont a mondat végén a `rejected_words` felsorolása előtt is. Ezekre a felesleges szóközökre nem sikerült a dolog logikájából jól kijövő megoldást találnom (annyit lehetne csinálni, hogy a `rejected_words` listát bevezető tabulátorhoz tartozó álszónak más címkét adok, mint a többinek, és akkor előrenézéssel látom, hogy előtte van vége a tulajdonképpeni mondatnak, de ez elég ad hocnak tűnt, ezért nem csináltam meg). Így a kiemelt szavak felsorolása előtti tabulátor előtt van mindig egy szóköz.

Ennek a szóköznek és az OCR során bekerült egyéb felesleges szóközöknek (nem tapadó írásjelek) a megoldására írtam még plusz egy kis szkriptet, ami regexekkel törli ezeket.

**Comment by gpetho** [comment]
> _"eltolódott a detok felé"_ Ez itt sztem kicsit YAGNI, de igaziból tök jó.

Közben az elmúlt két hétben új programkódot nem írtam, de azt próbáltam összerakni, hogy hogy lesz ebből (és az igekötőkapcsolóból és az összetételkezelésből) emtsv-modul. Ehhez próbáltam többek között az xtsv és az emtsv kódját olvasni, hogy megértsem, pontosan mit és hogyan csináltatok. Ez eddig leginkább demoralizáló volt, mert soronként ugyan (többnyire) még értem a kódot, de vagy nagyon bonyolult, vagy én nem vagyok elég okos hozzá, mindenesetre képtelen vagyok követni, hogy mi történik, és még ahol értem is, hogy mit csináltok, ott is egy csomó dolog van, amiről nem értem, hogy miért úgy csináltátok, ahogy.

Mindenesetre azt hiszem, az emtsv-modullá alakítás kapcsán válik fontossá az, hogy ne nyúljunk bele a meglévő mezőkbe, mert az xtsv dokumentációja kiköti a Data format szakaszban, hogy "Newly generated fields are started from the right of the rightmost column, the existing columns _should_ not be modified at all" (itt sem értem, hogy miért a _should_ van kiemelve; ezt akkor szokták így hangsúlyozni, ha azt akarják mondani, hogy lehetőleg ne, de az se baj, ha igen, ennek az olvasatnak viszont ellentmond a végén a hangsúlyos "at all"). Az utóbbi kitételt a filterben ugyan követtem (új oszlopot pedig egyáltalán nem adtam hozzá az outputhoz), de közben rájöttem, hogy még így sem lesz jó, az áltokeneket sem szabad alighanem beszúrni.

A filter ugyanis szerintem nem finalizer az xtsv fogalmai szerint, hanem belső modul. Például ha az eredeti ötleteteket követjük, hogy ti. dobjuk el az összes olyan mondatot a korpuszból, amiben az anas üres, akkor ugye a posnak ezeket a mondatokat felesleges eleve átadni, és megspórolunk egy csomó időt és energiát, ha már eleve csak a megrostált mondatok mennek tovább a posba. Ez a tok, morph, filter, pos sorrend lenne. Ha viszont bármilyen más modul a filter után van kötve, és a filter annotálta a továbbküldött mondatokat bármilyen módon, akkor az alighanem gondot fog okozni a jelen formában a downstream moduloknak.

Például tegyük fel, hogy csak elvált igekötőt tartalmazó mondatokat akarunk feldolgozni. Ebben az esetben rögtön a tok után beköthetünk egy filtert, ami rászűr (kereső üzemmódban) az igekötők listájára (_be, ki, meg_ stb.), ezeket meg is tageli, és így küldi tovább. A probléma ott kezdődik, hogy ezt nem tudjuk megtenni, mert a filter a FilterWord stb. címkéket az xpostagbe írná, ami viszont ezen a ponton még nincs is. Másrészt ha nem is ide írná, hanem teszem azt a formba (vagy egy lépéssel lentebb futtatva az anasba), akkor ha elérkezünk később a poshoz, ezek az álszavak a szófaji címkézőt bizonyára össze fogják zavarni. Tehát nem lenne szabad ott lenniük.

Erre az egészre azt a megoldást találtam, hogy mégse szúrjunk be álszavakat, hanem csináljunk egy filter oszlopot a filter modul outputjaként (ahogy eleve kellene az xtsv logikája szerint). Ide olyan kódok kerülnek, amik azt jelentik, hogy "pozitív/negatív mondat" és "tagelt szó". Ha a pipeline végén kvázi finalizerként bekötjük a `one_sentence_per_line`-t, akkor az értelmezi majd ezeket a kódokat és jeleníti meg a szimulált filter kért mondatcímkéit, a tageket a szavakon plusz a jelenlegi FilterListet. Ez az egész funkcionalitás tehát áttevődik ebbe az utóbbi szkriptbe.

Ezt még nem csináltam meg, de szerintem így kellene. Ennek az egésznek persze csak akkor van jelentősége és értelme (akkor viszont úgy gondolom, van), ha tényleg emtsv-modul a cél.
